USE [master]
GO

/****** Object:  Database [TheOne]    Script Date: 2016/6/12 下午 04:50:54 ******/
CREATE DATABASE [TheOne]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TheOne_Data', FILENAME = N'C:\Users\donlee\TheOne_Data.mdf' , SIZE = 9920KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TheOne_Log', FILENAME = N'C:\Users\donlee\TheOne_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TheOne].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TheOne] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TheOne] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TheOne] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TheOne] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TheOne] SET ARITHABORT OFF 
GO

ALTER DATABASE [TheOne] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TheOne] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TheOne] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TheOne] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TheOne] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TheOne] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TheOne] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TheOne] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TheOne] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TheOne] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TheOne] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TheOne] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TheOne] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TheOne] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TheOne] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TheOne] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TheOne] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TheOne] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TheOne] SET  MULTI_USER 
GO

ALTER DATABASE [TheOne] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TheOne] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TheOne] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TheOne] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TheOne] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TheOne] SET  READ_WRITE 
GO

